import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import RecoilContextProvider from '@/providers/RecoilContextProvider';
import { RecoilRoot } from 'recoil';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <RecoilContextProvider>{children}</RecoilContextProvider>
        {/* <RecoilRoot>{children}</RecoilRoot> */}
      </body>
    </html>
  );
}
